from fpdf import FPDF
from datetime import datetime

class PDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(30, 144, 255)  # DodgerBlue
        self.cell(0, 10, "AI Resume Screening Report", ln=True, align="C")
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(169, 169, 169)
        self.cell(0, 10, "Generated by AI Resume Screener", 0, 0, "C")

def generate_pdf(prediction, confidence, filepath):
    pdf = PDF()
    pdf.add_page()

    # Section Title
    pdf.set_fill_color(40, 40, 40)  # Dark gray section background
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Screening Result Summary", ln=True, fill=True)
    pdf.ln(6)

    # Resume Fit
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(0, 10, "Based on your resume, we recommend the following career role:")

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(0, 153, 0)  # Green
    pdf.cell(0, 10, f"Role: {prediction}", ln=True)
    pdf.ln(5)

    # Confidence Score
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(255, 140, 0)  # Orange
    pdf.cell(0, 10, f"Confidence Score: {confidence}%", ln=True)
    pdf.ln(8)

    # Date
    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%d %B %Y')}", ln=True)

    # Save PDF
    pdf.output(filepath)
